export const FETCH_ANNOUNCEMENTS_SUCCESS = 'FETCH_ANNOUNCEMENTS_SUCCESS';
export const FETCH_ANNOUNCEMENTS_FAILURE = 'FETCH_ANNOUNCEMENTS_FAILURE';
export const ADD_NEW_ANNOUNCEMENTS_SUCCESS = 'ADD_NEW_ANNOUNCEMENTS_SUCCESS';
export const ADD_NEW_ANNOUNCEMENTS_FAILURE = 'ADD_NEW_ANNOUNCEMENTS_FAILURE';
export const EDIT_ANNOUNCEMENTS_SUCCESS = 'EDIT_ANNOUNCEMENTS_SUCCESS';
export const EDIT_ANNOUNCEMENTS_FAILURE = 'EDIT_ANNOUNCEMENTS_FAILURE';
export const DELETE_ANNOUNCEMENTS_SUCCESS = 'DELETE_ANNOUNCEMENTS_SUCCESS';
export const DELETE_ANNOUNCEMENTS_FAILURE = 'DELETE_ANNOUNCEMENTS_FAILURE';
export const SET_EDIT_ANNOUNCEMENT_BUTTON_CLICKED = 'SET_EDIT_ANNOUNCEMENT_BUTTON_CLICKED';

export const FETCH_APARTMENTS_SUCCESS = 'FETCH_APARTMENTS_SUCCESS';
export const FETCH_APARTMENTS_FAILURE = 'FETCH_APARTMENTS_FAILURE';

export const FETCH_BUILDINGS_SUCCESS = 'FETCH_BUILDINGS_SUCCESS';
export const FETCH_BUILDINGS_FAILURE = 'FETCH_BUILDINGS_FAILURE';

export const FETCH_COSTS_SUCCESS = 'FETCH_COSTS_SUCCESS';
export const FETCH_COSTS_FAILURE = 'FETCH_COSTS_FAILURE';

export const FETCH_PAYMENT_ORDERS_SUCCESS = 'FETCH_PAYMENT_ORDERS_SUCCESS';
export const FETCH_PAYMENT_ORDERS_FAILURE = 'FETCH_PAYMENT_ORDERS_FAILURE';

export const FETCH_SNOW_CLEARING_SCHEDULES_SUCCESS = 'FETCH_SNOW_CLEARING_SCHEDULES_SUCCESS';
export const FETCH_SNOW_CLEARING_SCHEDULES_FAILURE = 'FETCH_SNOW_CLEARING_SCHEDULES_FAILURE';

export const FETCH_USER_NOTIFICATIONS_SUCCESS = 'FETCH_USER_NOTIFICATIONS_SUCCESS';
export const FETCH_USER_NOTIFICATIONS_FAILURE = 'FETCH_USER_NOTIFICATIONS_FAILURE';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const VALIDATE_USER_SUCCESS = 'VALIDATE_USER_SUCCESS';
export const VALIDATE_USER_FAILURE = 'VALIDATE_USER_FAILURE';

export const USER_INFO_TOGGLE = 'USER_INFO_TOGGLE';
export const USER_SETTINGS_TOGGLE = 'USER_SETTINGS_TOGGLE';

export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';

export const SET_INVALID_USER_NAME_AND_PASSWORD_VALUE = 'SET_INVALID_USER_NAME_AND_PASSWORD_VALUE';
