export const FETCH_ANNOUNCEMENTS_SUCCESS = 'FETCH_ANNOUNCEMENTS_SUCCESS';
export const FETCH_ANNOUNCEMENTS_FAILURE = 'FETCH_ANNOUNCEMENTS_FAILURE';
export const ADD_NEW_ANNOUNCEMENTS_SUCCESS = 'ADD_NEW_ANNOUNCEMENTS_SUCCESS';
export const ADD_NEW_ANNOUNCEMENTS_FAILURE = 'ADD_NEW_ANNOUNCEMENTS_FAILURE';
export const EDIT_ANNOUNCEMENTS_SUCCESS = 'EDIT_ANNOUNCEMENTS_SUCCESS';
export const EDIT_ANNOUNCEMENTS_FAILURE = 'EDIT_ANNOUNCEMENTS_FAILURE';
export const DELETE_ANNOUNCEMENTS_SUCCESS = 'DELETE_ANNOUNCEMENTS_SUCCESS';
export const DELETE_ANNOUNCEMENTS_FAILURE = 'DELETE_ANNOUNCEMENTS_FAILURE';
export const SET_EDIT_ANNOUNCEMENT_BUTTON_CLICKED = 'SET_EDIT_ANNOUNCEMENT_BUTTON_CLICKED';

export const FETCH_APARTMENTS_SUCCESS = 'FETCH_APARTMENTS_SUCCESS';
export const FETCH_APARTMENTS_FAILURE = 'FETCH_APARTMENTS_FAILURE';

export const FETCH_BUILDINGS_SUCCESS = 'FETCH_BUILDINGS_SUCCESS';
export const FETCH_BUILDINGS_FAILURE = 'FETCH_BUILDINGS_FAILURE';

export const FETCH_COSTS_SUCCESS = 'FETCH_COSTS_SUCCESS';
export const FETCH_COSTS_FAILURE = 'FETCH_COSTS_FAILURE';

export const FETCH_PAYMENT_ORDERS_SUCCESS = 'FETCH_PAYMENT_ORDERS_SUCCESS';
export const FETCH_PAYMENT_ORDERS_FAILURE = 'FETCH_PAYMENT_ORDERS_FAILURE';

export const FETCH_SNOW_CLEARING_SCHEDULES_SUCCESS = 'FETCH_SNOW_CLEARING_SCHEDULES_SUCCESS';
export const FETCH_SNOW_CLEARING_SCHEDULES_FAILURE = 'FETCH_SNOW_CLEARING_SCHEDULES_FAILURE';

export const FETCH_USER_NOTIFICATIONS_SUCCESS = 'FETCH_USER_NOTIFICATIONS_SUCCESS';
export const FETCH_USER_NOTIFICATIONS_FAILURE = 'FETCH_USER_NOTIFICATIONS_FAILURE';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const VALIDATE_USER_SUCCESS = 'VALIDATE_USER_SUCCESS';
export const VALIDATE_USER_FAILURE = 'VALIDATE_USER_FAILURE';

export const USER_INFO_TOGGLE = 'USER_INFO_TOGGLE';
export const USER_SETTINGS_TOGGLE = 'USER_SETTINGS_TOGGLE';

export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';

export const SET_INVALID_USER_NAME_AND_PASSWORD_VALUE = 'SET_INVALID_USER_NAME_AND_PASSWORD_VALUE';

export const GENERATE_SNOW_CLEARING_SCHEDULE_SUCCESS = 'GENERATE_SNOW_CLEARING_SCHEDULE_SUCCESS';
export const GENERATE_SNOW_CLEARING_SCHEDULE_FAILURE = 'GENERATE_SNOW_CLEARING_SCHEDULE_FAILURE';
export const TOGGLE_GENERATE_SNOW_CLEARING_SCHEDULE_BUTTON = 'TOGGLE_GENERATE_SNOW_CLEARING_SCHEDULE_BUTTON';
export const ASK_CHANGE_SUCCESS = 'ASK_CHANGE_SUCCESS';
export const ASK_CHANGE_FAILURE = 'ASK_CHANGE_FAILURE';
export const APPROVE_CHANGE_REQUEST_SUCCESS = 'APPROVE_CHANGE_REQUEST_SUCCESS';
export const APPROVE_CHANGE_REQUEST_FAILURE = 'APPROVE_CHANGE_REQUEST_FAILURE';
export const TOGGLE_APPROVE_REQUEST_CHANGE = 'TOGGLE_APPROVE_REQUEST_CHANGE';

export const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS';
export const ADD_NEW_USER_FAILURE = 'ADD_NEW_USER_FAILURE';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
export const EDIT_USER_INFO_SUCCESS = 'EDIT_USER_INFO_SUCCESS';
export const EDIT_USER_INFO_FAILURE = 'EDIT_USER_INFO_FAILURE';

